version: '3.8'

services:
  ubuntu:
    build:
      context: .
      dockerfile: ubuntu.Dockerfile
    container_name: droplet
    stdin_open: true
    tty: true
    volumes:
      # Mount your local dotfiles directory into /root/dotfiles in the container
      - ~/dotfiles:/root/dotfiles
